export declare const DefaultDemoCode = "import React from 'react';\n// Load umd modules support `unpkg` like ant-design automatically, you just need to import it.\n// Others umd modules without `unpkg` field in package.json, you can specific path manually.\nimport { Form, Button, Modal, Input } from 'antd';\nimport HelloModule from 'hello-module';\n\nconst { Item, useForm, useWatch } = Form;\n\nconst App = (props) => {\n    const [form] = useForm();\n    const username = useWatch('username', form);\n    \n    const onFinish = () => {\n        const password = form.getFieldValue('password');\n        if (password !== '123456') {\n            Modal.error({\n                title: '\u767B\u5F55\u5931\u8D25',\n                content: '\u767B\u5F55\u5931\u8D25\uFF0C\u5BC6\u7801\u9519\u8BEF\uFF01'\n            });\n            return;\n        }\n        Modal.success({\n            title: '\u767B\u5F55\u6210\u529F',\n            content: '\u767B\u5F55\u6210\u529F'\n        });\n    };\n\n    return (\n        <div style={{ textAlign: 'center' }}>\n            <HelloModule/>\n            <div className=\"title\">title class</div>\n            <Form\n                form={form}\n                onFinish={onFinish}\n                labelCol={{ span: 4 }}\n                wrapperCol={{ span: 20 }}\n            >\n                <Item label=\"\u7528\u6237\u540D\" name=\"username\">\n                    <Input placeholder=\"\u8BF7\u8F93\u5165\u7528\u6237\u540D\"/>\n                </Item>\n                <Item label=\"\u5BC6\u7801\" name=\"password\">\n                    <Input type=\"password\" placeholder={`\u8BF7\u8F93\u5165 ${username} \u7684\u5BC6\u7801`} />\n                </Item>\n                <Item>\n                    <Button type=\"primary\" htmlType=\"submit\">\u63D0\u4EA4</Button>\n                </Item>\n            </Form>\n        </div>\n    );\n}\nexport default App;";
export declare const DefaultIndexCode = "import React from 'react';\nimport ReactDom from 'react-dom';\nimport App from './App';\n\nReactDom.render(<App/>, document.getElementById('root'));";
export declare const DepsCommonHeader = "//============================================================\n// Do not modify following import and export statements\nimport * as React from 'react';\nimport { define, _import } from 'module-manager';\nexport default 'module-valid';\n//=============================================================\n// \uD83D\uDE80\uD83D\uDE80 Declare where to insert module script tags.\nexport const body = document.body;\n\n// \uD83D\uDE80\uD83D\uDE80 This is a function declared how to resolve module script when require a module doesn't exist.\n// export async function resolve(packageName, version, file) {\n//     const versionSuffix = version ? `@${version}` : '';\n//     const fileSuffix = file ? `${file}` : '';\n//     // `return false` to cancel auto require deps.\n//     return `https://unpkg.com/${packageName}${versionSuffix}${fileSuffix}`;\n// }\n\n// \uD83D\uDE80\uD83D\uDE80 You can define your dependencies here:\ndefine('version', [], () => ({ 'default': '1.0.0' }));\n";
export declare const DefaultDepsCode: string;
export declare const DefaultCssCode = ".title { color: blue }";
export declare const Placeholder = "<h3> \uD83D\uDE80 Welcome to use code sandbox. </h3>";
export declare const formatDeps: (deps: Array<{
    url: string;
    obj: string;
    id: string;
}>) => string;
