/*
 * @Description: passage
 * @Author: 张盼宏
 * @Date: 2022-08-27 23:24:29
 * @LastEditors: 张盼宏
 * @LastEditTime: 2022-08-28 02:05:29
 */
import { useEffect } from 'react';

import {usePageConfig} from "@/hooks";

import styles from './style.module.less';

export default function Passage () {
    const { setStates } = usePageConfig();

    useEffect(() => {
        setStates?.({
            title: '文章标题'
        });
    }, [setStates]);

    return (
        <div className={styles.passageContainer}>
            <div className={styles.passage}>
                <div>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                </div>
                <div>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                </div>
                <div>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                </div>
                <div>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                </div>
                <div>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                </div>
                <div>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                </div>
                <div>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                </div>
                <div>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                </div>
                <div>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                </div>
                <div>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                </div>
                <div>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                </div>
                <div>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                </div>
                <div>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                </div>
                <div>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                </div>
                <div>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                </div>
                <div>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                </div>
                <div>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                </div>
                <div>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                </div>
                <div>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                </div>
                <div>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                </div>
                <div>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                </div>
                <div>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                </div>
                <div>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                </div>
                <div>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                </div>
                <div>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                </div>
                <div>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                </div>
                <div>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                </div>
                <div>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                </div>
                <div>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                </div>
                <div>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                </div>
                <div>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                </div>
                <div>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                </div>
                <div>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                </div>
                <div>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                </div>
                <div>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                </div>
                <div>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                </div>
                <div>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                </div>
                <div>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                </div>
                <div>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                </div>
                <div>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                </div>
                <div>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                </div>
                <div>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                </div>
                <div>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                </div>
                <div>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                </div>
                <div>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                </div>
                <div>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                </div>
                <div>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                </div>
                <div>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                </div>
                <div>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                </div>
                <div>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                </div>
                <div>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                </div>
                <div>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                </div>
                <div>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                </div>
                <div>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                </div>
                <div>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                </div>
                <div>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                </div>
                <div>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                </div>
                <div>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                </div>
                <div>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                </div>
                <div>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                    <span>这个是文章的内容</span>
                </div>
            </div>
        </div>
    );
}
